# Generated by Django 3.0.5 on 2020-05-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
        ('companions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionToOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=1)),
                ('cost_of_sale', models.PositiveIntegerField(default=1)),
                ('companion_percent', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companions.Companion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.Order')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='positions.Position')),
            ],
        ),
        migrations.CreateModel(
            name='DetailToOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('address_delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('sale', models.PositiveIntegerField(default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='CompanionToOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_work', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=0)),
                ('companion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companions.Companion')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion', to='orders.Order')),
            ],
        ),
    ]
