# Generated by Django 3.0.5 on 2020-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailtoorder',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailtoorder',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
