# Generated by Django 3.0.5 on 2020-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=1)),
                ('cost_of_sale', models.PositiveIntegerField(default=1)),
                ('alias_id', models.CharField(max_length=24, unique=True)),
            ],
        ),
    ]
